import { sql } from "drizzle-orm";
import { sqliteTable, text, integer } from "drizzle-orm/sqlite-core";

/** ISO-8601 UTC timestamp, generated by SQLite. */
const nowIso = sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`;

/** Client — auto-created/matched by CNP. Retained (operational + reminders). */
export const clients = sqliteTable("clients", {
  id: text("id").primaryKey(),
  cnp: text("cnp").unique(),
  nume: text("nume"),
  prenume: text("prenume"),
  sex: text("sex"),
  dataNasterii: text("data_nasterii"),
  telefon: text("telefon"),
  email: text("email"),
  adresaJson: text("adresa_json"),
  actJson: text("act_json"),
  createdAt: text("created_at").default(nowIso).notNull(),
  updatedAt: text("updated_at").default(nowIso).notNull(),
});

export const vehicles = sqliteTable("vehicles", {
  id: text("id").primaryKey(),
  clientId: text("client_id").references(() => clients.id),
  plate: text("plate"),
  vin: text("vin"),
  marca: text("marca"),
  model: text("model"),
  anFabricatie: text("an_fabricatie"),
  dataJson: text("data_json"),
  createdAt: text("created_at").default(nowIso).notNull(),
});

/** A dosar = one processing case (one client's set of photos). */
export const dosare = sqliteTable("dosare", {
  id: text("id").primaryKey(),
  // primit | in_procesare | de_verificat | gata | emis
  status: text("status").notNull().default("primit"),
  clientId: text("client_id").references(() => clients.id),
  minutesSavedEst: integer("minutes_saved_est"),
  notes: text("notes"),
  createdAt: text("created_at").default(nowIso).notNull(),
  processedAt: text("processed_at"),
  emisAt: text("emis_at"),
});

/** Raw photo — file lives on disk; purged_at set when the image is deleted (GDPR). */
export const photos = sqliteTable("photos", {
  id: text("id").primaryKey(),
  dosarId: text("dosar_id")
    .notNull()
    .references(() => dosare.id),
  filepath: text("filepath").notNull(),
  docType: text("doc_type"), // buletin | talon | permis | policy | junk
  uploadedAt: text("uploaded_at").default(nowIso).notNull(),
  purgedAt: text("purged_at"),
});

/** Structured extraction per document, with per-field confidence. */
export const extractions = sqliteTable("extractions", {
  id: text("id").primaryKey(),
  dosarId: text("dosar_id")
    .notNull()
    .references(() => dosare.id),
  photoId: text("photo_id").references(() => photos.id),
  docType: text("doc_type").notNull(),
  fieldsJson: text("fields_json").notNull(),
  confidenceJson: text("confidence_json"),
  modelUsed: text("model_used"),
  createdAt: text("created_at").default(nowIso).notNull(),
});

/** Issued policy — the registry that powers v1.5 reminders. */
export const policies = sqliteTable("policies", {
  id: text("id").primaryKey(),
  dosarId: text("dosar_id").references(() => dosare.id),
  clientId: text("client_id").references(() => clients.id),
  vehicleId: text("vehicle_id").references(() => vehicles.id),
  policyNumber: text("policy_number"),
  insurer: text("insurer"),
  type: text("type"), // rca | pad | facultativ
  validFrom: text("valid_from"),
  validTo: text("valid_to"),
  source: text("source"), // pdf | manual
  createdAt: text("created_at").default(nowIso).notNull(),
});
